import { DrugItem, Patient, Appointment, PaymentRecord, HeaderSettings, PageSetupSettings } from './types';

export const INITIAL_DRUGS: DrugItem[] = [
  { brand: "Napa Extend 665mg", generic: "Paracetamol", indication: "Fever, Osteoarthritis, Backache", drugClass: "Analgesics", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Napa Rapid 500mg", generic: "Paracetamol", indication: "Mild to moderate pain, fever", drugClass: "Analgesics", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Napa 500mg", generic: "Paracetamol", indication: "Fever, simple headache", drugClass: "Analgesics", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Napa Extra", generic: "Paracetamol + Caffeine", indication: "Severe headache, toothache, fever", drugClass: "Analgesics", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Ace Plus 500mg/65mg", generic: "Paracetamol + Caffeine", indication: "Headache, joint pain, migraine", drugClass: "Analgesics", company: "Square Pharmaceuticals Ltd." },
  { brand: "Fast 500mg", generic: "Paracetamol", indication: "Fever, pain management", drugClass: "Analgesics", company: "Acme Laboratories Ltd." },
  { brand: "Ketorol 10mg", generic: "Ketorolac Tromethamine", indication: "Short-term moderate to severe pain", drugClass: "NSAIDs", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Rolac 10mg", generic: "Ketorolac Tromethamine", indication: "Acute pain, dental pain", drugClass: "NSAIDs", company: "Renata Limited" },
  { brand: "Torax 10mg", generic: "Ketorolac Tromethamine", indication: "Severe inflammatory pain", drugClass: "NSAIDs", company: "Square Pharmaceuticals Ltd." },
  
  { brand: "Seclo 20mg", generic: "Omeprazole", indication: "GERD, Peptic Ulcer, Gastric Acidity", drugClass: "Proton Pump Inhibitors", company: "Square Pharmaceuticals Ltd." },
  { brand: "Seclo 40mg (DR)", generic: "Omeprazole", indication: "Severe hyperacidity, duodenal ulcer", drugClass: "Proton Pump Inhibitors", company: "Square Pharmaceuticals Ltd." },
  { brand: "Nexum 20mg", generic: "Esomeprazole", indication: "Acid dyspepsia, GERD", drugClass: "Proton Pump Inhibitors", company: "ACI Healthcare" },
  { brand: "Nexum 40mg", generic: "Esomeprazole", indication: "Duodenal Ulcer, Acid Reflux", drugClass: "Proton Pump Inhibitors", company: "ACI Healthcare" },
  { brand: "Sergel 20mg", generic: "Esomeprazole", indication: "Acid Peptic Disorders, Erosive Esophagitis", drugClass: "Proton Pump Inhibitors", company: "Healthcare Pharmaceuticals Ltd." },
  { brand: "Sergel 40mg (IV)", generic: "Esomeprazole", indication: "Severe GERD, bleeding peptic ulcer", drugClass: "Proton Pump Inhibitors", company: "Healthcare Pharmaceuticals Ltd." },
  { brand: "Maxpro 20mg", generic: "Esomeprazole", indication: "Duodenal and Gastric Ulcer", drugClass: "Proton Pump Inhibitors", company: "Renata Limited" },
  { brand: "Maxpro 40mg", generic: "Esomeprazole", indication: "Severe acid reflux, erosive esophagitis", drugClass: "Proton Pump Inhibitors", company: "Renata Limited" },
  { brand: "Finix 20mg", generic: "Rabeprazole Sodium", indication: "Active duodenal ulcer, GERD", drugClass: "Proton Pump Inhibitors", company: "Opsonin Pharma Ltd." },
  { brand: "Finix 40mg", generic: "Rabeprazole Sodium", indication: "Zollinger-Ellison syndrome", drugClass: "Proton Pump Inhibitors", company: "Opsonin Pharma Ltd." },

  { brand: "Alatrol 10mg", generic: "Cetirizine Hydrochloride", indication: "Allergic Rhinitis, Urticaria", drugClass: "Antihistamines", company: "Square Pharmaceuticals Ltd." },
  { brand: "Fexo 120mg", generic: "Fexofenadine Hydrochloride", indication: "Seasonal Allergic Rhinitis", drugClass: "Antihistamines", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Fexo 180mg", generic: "Fexofenadine Hydrochloride", indication: "Chronic Idiopathic Urticaria, Allergies", drugClass: "Antihistamines", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Fenadin 120mg", generic: "Fexofenadine", indication: "Sneezing, Runny Nose, Skin Itch", drugClass: "Antihistamines", company: "Renata Limited" },
  { brand: "Rulox 10mg", generic: "Rupatadine", indication: "Allergic Rhinitis, Hives", drugClass: "Antihistamines", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Rulox 20mg", generic: "Rupatadine", indication: "Allergic Rhinitis, Hives", drugClass: "Antihistamines", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Telfast 120mg", generic: "Fexofenadine Hydrochloride", indication: "Allergy symptoms, skin rashes", drugClass: "Antihistamines", company: "Sanofi Bangladesh Ltd." },

  { brand: "Atova 10mg", generic: "Atorvastatin", indication: "Hypercholesterolaemia, Cardiovascular prevention", drugClass: "Statins", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Atova 20mg", generic: "Atorvastatin", indication: "Severe Hypercholesterolaemia", drugClass: "Statins", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Rosuva 10mg", generic: "Rosuvastatin", indication: "Hyperlipidaemia, Atherosclerosis", drugClass: "Statins", company: "Square Pharmaceuticals Ltd." },
  { brand: "Rosuva 5mg", generic: "Rosuvastatin", indication: "Moderate hyperlipidaemia", drugClass: "Statins", company: "Square Pharmaceuticals Ltd." },
  { brand: "Rosuva 20mg", generic: "Rosuvastatin", indication: "Severe cardiovascular hyperlipidemia", drugClass: "Statins", company: "Square Pharmaceuticals Ltd." },

  { brand: "Monas 10mg", generic: "Montelukast", indication: "Asthma Prophylaxis, Allergic Bronchospasm", drugClass: "Leukotriene Receptor Antagonists", company: "Acme Laboratories Ltd." },
  { brand: "Monas 5mg", generic: "Montelukast", indication: "Pediatric Asthma, seasonal allergies", drugClass: "Leukotriene Receptor Antagonists", company: "Acme Laboratories Ltd." },
  { brand: "Monas 4mg (Chewable)", generic: "Montelukast", indication: "Pediatric asthma prophylaxis", drugClass: "Leukotriene Receptor Antagonists", company: "Acme Laboratories Ltd." },
  { brand: "Airlc 10mg", generic: "Montelukast", indication: "Chronic Asthma, Seasonal Allergies", drugClass: "Leukotriene Receptor Antagonists", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Provair 10mg", generic: "Montelukast", indication: "Bronchial Asthma and Rhinitis", drugClass: "Leukotriene Receptor Antagonists", company: "Radiant Pharmaceuticals Ltd." },

  { brand: "Tufnil 200mg", generic: "Tolfenamic Acid", indication: "Acute Migraine, Severe Headache", drugClass: "NSAIDs", company: "Eskayef Pharmaceuticals Ltd." },
  { brand: "Zimax 500mg", generic: "Azithromycin", indication: "Bacterial Bronchitis, Pneumonia, Tonsillitis", drugClass: "Macrolide Antibiotics", company: "Square Pharmaceuticals Ltd." },
  { brand: "Zimax 200mg/5ml (Syp)", generic: "Azithromycin", indication: "Pediatric bacterial infections", drugClass: "Macrolide Antibiotics", company: "Square Pharmaceuticals Ltd." },
  { brand: "Cef-3 200mg", generic: "Cefixime Trihydrate", indication: "Urinary tract infections, Otitis media", drugClass: "Cephalosporin Antibiotics", company: "Square Pharmaceuticals Ltd." },
  { brand: "Cef-3 400mg", generic: "Cefixime Trihydrate", indication: "Typhoid fever, respiratory infections", drugClass: "Cephalosporin Antibiotics", company: "Square Pharmaceuticals Ltd." },
  { brand: "Ciprocin 500mg", generic: "Ciprofloxacin", indication: "Urethritis, Typhoid fever, severe UTI", drugClass: "Quinolone Antibiotics", company: "Square Pharmaceuticals Ltd." },
  { brand: "Neofloxin 500mg", generic: "Ciprofloxacin", indication: "Bacterial diarrhea, bone & joint infection", drugClass: "Quinolone Antibiotics", company: "Beximco Pharmaceuticals Ltd." },

  { brand: "Fixocard 5mg", generic: "Amlodipine Besylate", indication: "Hypertension, Chronic Stable Angina", drugClass: "Calcium Channel Blockers", company: "Acme Laboratories Ltd." },
  { brand: "Camlodin 5mg", generic: "Amlodipine", indication: "High blood pressure control", drugClass: "Calcium Channel Blockers", company: "Square Pharmaceuticals Ltd." },
  { brand: "Angilock 50mg", generic: "Losartan Potassium", indication: "Hypertension, Diabetic Nephropathy", drugClass: "Angiotensin II Receptor Blockers", company: "Square Pharmaceuticals Ltd." },
  { brand: "Angilock Plus 50/12.5mg", generic: "Losartan + Hydrochlorothiazide", indication: "Severe multi-drug hypertension", drugClass: "Angiotensin II Receptor Blockers", company: "Square Pharmaceuticals Ltd." },
  { brand: "Bipro 2.5mg", generic: "Bisoprolol Fumarate", indication: "Moderate heart failure, hypertension", drugClass: "Beta-blockers", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Bipro 5mg", generic: "Bisoprolol Fumarate", indication: "Chronic stable angina", drugClass: "Beta-blockers", company: "Incepta Pharmaceuticals Ltd." },

  { brand: "Metfora 850mg", generic: "Metformin Hydrochloride", indication: "Type 2 Diabetes Mellitus Control", drugClass: "Biguanides", company: "Beximco Pharmaceuticals Ltd." },
  { brand: "Compaa 500mg", generic: "Metformin Hydrochloride", indication: "Type 2 Diabetes Mellitus glycemic control", drugClass: "Biguanides", company: "Square Pharmaceuticals Ltd." },
  { brand: "Secrin 2mg", generic: "Glimepiride", indication: "Type 2 Diabetes Mellitus", drugClass: "Sulfonylureas", company: "Square Pharmaceuticals Ltd." },
  { brand: "Secrin 1mg", generic: "Glimepiride", indication: "Mild Type 2 Diabetes Mellitus", drugClass: "Sulfonylureas", company: "Square Pharmaceuticals Ltd." },
  { brand: "Glyta 50mg", generic: "Vildagliptin", indication: "Type 2 Diabetes glycemic control", drugClass: "DPP-4 Inhibitors", company: "Incepta Pharmaceuticals Ltd." },

  { brand: "Bicozazin (Tab)", generic: "Zinc + Vitamin B-Complex", indication: "Vitamin deficiency, weakness", drugClass: "Vitamins & Minerals", company: "Square Pharmaceuticals Ltd." },
  { brand: "A-Card 75mg", generic: "Aspirin", indication: "Antiplatelet, Cardiovascular prevention", drugClass: "Antiplatelets", company: "Square Pharmaceuticals Ltd." },
  { brand: "Clopid 75mg", generic: "Clopidogrel", indication: "Prophylaxis of thromboembolic events", drugClass: "Antiplatelets", company: "Incepta Pharmaceuticals Ltd." },
  { brand: "Coral-D (Tab)", generic: "Calcium Carbonate + Vitamin D3", indication: "Osteoporosis, calcium deficiency", drugClass: "Vitamins & Minerals", company: "Square Pharmaceuticals Ltd." },
  { brand: "Calbo-D (Tab)", generic: "Calcium Carbonate + Vitamin D3", indication: "Bone health, calcium supplements", drugClass: "Vitamins & Minerals", company: "Square Pharmaceuticals Ltd." },
  { brand: "Neuro-B (Tab)", generic: "Vitamin B1 + B6 + B12", indication: "Neuropathic pain, vitamin B deficiency", drugClass: "Vitamins & Minerals", company: "Square Pharmaceuticals Ltd." },
  { brand: "Filwel Silver", generic: "Multivitamin & Multimineral 50+", indication: "Nutritional supplement for age 50+", drugClass: "Vitamins & Minerals", company: "Square Pharmaceuticals Ltd." },
  { brand: "Bextrum Gold", generic: "A-Z Multivitamin & Minerals", indication: "Essential vitamin booster for adult energy", drugClass: "Vitamins & Minerals", company: "Beximco Pharmaceuticals Ltd." },

  { brand: "Xeldrin 100ml (Syp)", generic: "Ambroxol Hydrochloride", indication: "Productive cough, chest congestion", drugClass: "Cough & Cold Preparations", company: "Square Pharmaceuticals Ltd." },
  { brand: "Adryl 100ml (Syp)", generic: "Diphenhydramine Hydrochloride", indication: "Dry cough, allergy control", drugClass: "Cough & Cold Preparations", company: "Square Pharmaceuticals Ltd." },
  { brand: "Tuska 100ml (Syp)", generic: "Guaiphenesin + Levomenthol", indication: "Sore throat, wet chest cough relief", drugClass: "Cough & Cold Preparations", company: "Square Pharmaceuticals Ltd." },
  { brand: "Gavisol 200ml (Syp)", generic: "Sodium Alginate + Sodium Bicarbonate", indication: "Heartburn, acid indigestion", drugClass: "Antacids", company: "Square Pharmaceuticals Ltd." },
  { brand: "Windel 100ml (Syp)", generic: "Salbutamol", indication: "Asthmatic bronchospasm relief", drugClass: "Bronchodilators", company: "Square Pharmaceuticals Ltd." },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "pat-1",
    name: "Musafir Muhammad",
    age: "32",
    sex: "M",
    address: "Gaibandha, Rangpur",
    mobile: "01700000000",
    regNo: "112589",
    date: "2026-05-19",
    dx: "Essential Hypertension & Acid Peptic Disease",
    cc: "1. Mild severe headache for 3 days.\n2. Burning sensations in chest & throat with occasional sour belches.\n3. Flatulence & abdominal bloating after taking oily food.",
    bp: "135/85 mmHg",
    pulse: "78",
    temp: "98.6°F",
    heart: "S1+S2+M0",
    lungs: "NAD",
    abd: "Soft, Non-Tender",
    anaemia: "Mild",
    jaundice: "Nil",
    cyanosis: "Nil",
    oedema: "Nil",
    ix: "1. Complete Blood Count (CBC)\n2. Fasting Blood Sugar (FBS)\n3. Serum Lipids Profile\n4. ECG (12-Lead)",
    drugHistory: "Takes over-the-counter Seclo 20mg occasionally. Napa Extend for headaches.",
    pastHistory: "No history of Asthma, Diabetes or Tuberculosis.",
    presentHistory: "Experiencing elevated blood pressure during stressful workspace schedules.",
    notes: "Patient is advised to maintain a low-salt diet and exercise at least 30 minutes daily.",
    
    // Calculators initialization
    bmiWeight: "75",
    bmiHeightFeet: "5",
    bmiHeightInch: "8",
    bmiValue: "25.1",
    bmiClass: "Overweight",
    bmiIdealWeight: "60-72 kg",

    insulinWeight: "75",
    insulinUnitPerKg: "0.3",
    insulinTime: "BD",
    insulinTotalUnit: "22.5",
    insulinDose: "11-0-11 Units",

    zDob: "1994-05-10",
    zGender: "M",
    zWeight: "75",
    zResult: "Perfect",
    zDays: "11696",

    bmrWeight: "75",
    bmrHeightFeet: "5",
    bmrHeightInch: "8",
    bmrGender: "M",
    bmrAge: "32",
    bmrActivity: "No Exercise",
    bmrValue: "1675 kcal/day",

    eddLmp: "2026-02-14",
    eddGestationalAge: "13 weeks 3 days",
    eddCalculatedDate: "2026-11-21",

    printPastHist: false,
    printPresentHist: true,
    printNotesSettings: true,
    printEddSettings: false
  },
  {
    id: "pat-2",
    name: "Rabeya Begum",
    age: "45",
    sex: "F",
    address: "Panthapath, Dhaka",
    mobile: "01617180711",
    regNo: "145162",
    date: "2026-05-18",
    dx: "Type 2 Diabetes Mellitus & Obesity",
    cc: "1. Polyuria and excessive thirst for 2 months.\n2. General weakness and lethargy.\n3. Numbness in extremities.",
    bp: "120/80 mmHg",
    pulse: "72",
    temp: "98.4°F",
    heart: "NAD",
    lungs: "NAD",
    abd: "Soft",
    anaemia: "Nil",
    jaundice: "Nil",
    cyanosis: "Nil",
    oedema: "Nil",
    ix: "1. HbA1c\n2. S. Creatinine\n3. Urine RE",
    drugHistory: "None",
    pastHistory: "Asthma in childhood, now controlled.",
    presentHistory: "Insidious onset of lethargy with high carbohydrate food diet habits.",
    notes: "Requires strict carbohydrate logging.",
    
    bmiWeight: "82",
    bmiHeightFeet: "5",
    bmiHeightInch: "2",
    bmiValue: "33.6",
    bmiClass: "Obese (Class 1)",
    bmiIdealWeight: "47-59 kg",

    insulinWeight: "82",
    insulinUnitPerKg: "0.2",
    insulinTime: "BD",
    insulinTotalUnit: "16.4",
    insulinDose: "8-0-8 Units",

    zDob: "1981-08-15",
    zGender: "F",
    zWeight: "82",
    zResult: "High Risk",
    zDays: "16348",

    bmrWeight: "82",
    bmrHeightFeet: "5",
    bmrHeightInch: "2",
    bmrGender: "F",
    bmrAge: "45",
    bmrActivity: "Light Exercise",
    bmrValue: "1450 kcal/day",

    eddLmp: "",
    eddGestationalAge: "",
    eddCalculatedDate: "",

    printPastHist: true,
    printPresentHist: true,
    printNotesSettings: true,
    printEddSettings: false
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  { id: "ap-1", date: "2026-05-20", status: "Pending", serial: 1, regNo: "145162", apntNo: "APN-902", name: "Rabeya Begum", age: "45", sex: "F", mobile: "01617180711", address: "Dhaka", paid: "300" },
  { id: "ap-2", date: "2026-05-20", status: "Completed", serial: 2, regNo: "112589", apntNo: "APN-903", name: "Musafir Muhammad", age: "32", sex: "M", mobile: "01700000000", address: "Gaibandha", paid: "300" },
  { id: "ap-3", date: "2026-05-21", status: "Pending", serial: 3, regNo: "115201", apntNo: "APN-904", name: "Anisur Rahman", age: "50", sex: "M", mobile: "01815667788", address: "Rangpur", paid: "300" }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  { id: "pay-1", date: "2026-05-19", regNo: "112589", name: "Musafir Muhammad", address: "Gaibandha, Rangpur", mobile: "01700000000", amount: "300" },
  { id: "pay-2", date: "2026-05-18", regNo: "145162", name: "Rabeya Begum", address: "Panthapath, Dhaka", mobile: "01617180711", amount: "300" }
];

export const INITIAL_HEADER_SETTINGS: HeaderSettings = {
  doctorName: "Dr. Musafir Muhammad",
  degrees: "MBBS (Rangpur Medical College), MD (Cardiology)",
  specialty: "Medicine Specialist & Cardiologist",
  department: "Department of Medicine",
  medicalCollege: "Rangpur Medical College & Hospital",
  bmdcReg: "BMDC Reg. No- 112589",
  clinicName: "Crescent Diagnostic Center & Chamber",
  clinicAddress: "Panthapath, Dhaka-1205",
  clinicMobile: "+8801700000000",
  visitTime: "Visit Time: 4PM - 10PM",
  offDay: "Friday Off",
  backgroundColor: "#E9E9E9",
  footerText: "নিয়ম মাফিক ঔষধ খাইবেন। ডাক্তারের পরামর্শ ব্যতীত ঔষধ পরিবর্তন নিষেধ।",
  displayBarcode: true
};

export const INITIAL_PAGE_SETUP: PageSetupSettings = {
  header: { height: 5.7, width: 21.1 },
  patient: { height: 1.6, width: 21.1 },
  history: { height: 19.0, width: 7.6 },
  mainPad: { height: 19.0, width: 13.3 },
  footer: { height: 1.0, width: 21.1 },
  totalPage: { height: 29.6, width: 21.3 },
  printFontSize: 12,
  linesPerPage: 32,
  visitFees: 300,
  reVisitFees: 200,
  reVisitValidity: 90,
  defaultRevisitText: "পর আসবেন।",
  printBarcode: true,
  barcodePosition: "Left Bottom",
  multipagePrint: true,
  displayVisitNo: true,
  printPatientInfo: true,
  displayTextRx: true,
  displayFieldCheckboxes: {
    name: true,
    age: true,
    sex: true,
    weight: true,
    date: true,
    address: true,
    regNo: true,
    mobile: true,
    cc: true,
    oe: true,
    advice: true,
    dx: true,
    footer: true
  }
};
